import {
  ConfigPlugin,
  withProjectBuildGradle,
} from '@expo/config-plugins';
import type { PluginConfig } from '../schema';

/**
 * Adds Maven repositories and vendor Gradle plugin classpaths to root build.gradle.
 * Idempotent. Supports the Groovy build.gradle generated by Expo prebuild.
 */
export const withDooPushRootBuildGradle: ConfigPlugin<PluginConfig> = (config, validated) => {
  return withProjectBuildGradle(config, (cfg) => {
    let contents = cfg.modResults.contents;

    const addAllProjectsRepo = (repo: string, marker: string) => {
      const allprojectsStart = contents.search(/allprojects\s*{/);
      if (allprojectsStart >= 0) {
        const searchArea = contents.slice(allprojectsStart);
        if (searchArea.includes(marker)) return;
      }

      contents = contents.replace(
        /allprojects\s*{\s*repositories\s*{/,
        `allprojects {\n    repositories {\n        ${repo}`
      );
    };

    const addBuildscriptRepo = (repo: string, marker: string) => {
      const buildscriptRegex = /buildscript\s*{[\s\S]*?repositories\s*{/;
      const buildscriptStart = contents.search(/buildscript\s*{/);
      if (buildscriptStart >= 0) {
        const afterBuildscript = contents.slice(buildscriptStart);
        const dependenciesStart = afterBuildscript.search(/dependencies\s*{/);
        const searchArea = dependenciesStart >= 0
          ? afterBuildscript.slice(0, dependenciesStart)
          : afterBuildscript.split(/allprojects\s*{/)[0];
        if (searchArea.includes(marker)) return;
      }


      if (buildscriptRegex.test(contents)) {
        contents = contents.replace(buildscriptRegex, (match) => `${match}\n        ${repo}`);
      } else if (/buildscript\s*{/.test(contents)) {
        contents = contents.replace(/buildscript\s*{/, `buildscript {\n    repositories {\n        ${repo}\n    }`);
      } else {
        contents = `buildscript {\n    repositories {\n        ${repo}\n    }\n}\n\n${contents}`;
      }
    };

    const addClasspath = (dependency: string) => {
      const artifact = dependency.match(/'([^:]+:[^:]+):/)?.[1] ?? dependency;
      if (contents.includes(artifact)) return;

      if (/buildscript\s*{[\s\S]*?dependencies\s*{/.test(contents)) {
        contents = contents.replace(/(buildscript\s*{[\s\S]*?dependencies\s*{)/, `$1\n        classpath ${dependency}`);
      } else if (/buildscript\s*{/.test(contents)) {
        contents = contents.replace(/buildscript\s*{/, `buildscript {\n    dependencies {\n        classpath ${dependency}\n    }`);
      } else {
        contents = `buildscript {\n    dependencies {\n        classpath ${dependency}\n    }\n}\n\n${contents}`;
      }
    };

    addAllProjectsRepo(`maven { url 'https://jitpack.io' }`, 'jitpack.io');

    if (validated.android.vendors.fcm) {
      addClasspath("'com.google.gms:google-services:4.4.2'");
    }

    if (validated.android.vendors.hms) {
      const huaweiRepo = `maven { url 'https://developer.huawei.com/repo/' }`;
      addAllProjectsRepo(huaweiRepo, 'developer.huawei.com/repo');
      addBuildscriptRepo(huaweiRepo, 'developer.huawei.com/repo');
      addClasspath("'com.huawei.agconnect:agcp:1.9.3.302'");
    }

    if (validated.android.vendors.honor) {
      const honorRepo = `maven { url 'https://developer.hihonor.com/repo/' }`;
      addAllProjectsRepo(honorRepo, 'developer.hihonor.com/repo');
      addBuildscriptRepo(honorRepo, 'developer.hihonor.com/repo');
      addClasspath("'com.hihonor.mcs:asplugin:2.0.1.300'");
    }

    // mavenLocal for development.
    addAllProjectsRepo('mavenLocal()', 'mavenLocal()');

    cfg.modResults.contents = contents;
    return cfg;
  });
};
