import {
  ConfigPlugin,
  withProjectBuildGradle,
} from '@expo/config-plugins';
import type { PluginConfig } from '../schema';
import * as fs from 'fs';
import * as path from 'path';

/**
 * Honor's asplugin requires an explicit AGP classpath version in root build.gradle.
 * Expo SDK ≥54 declares AGP without a version (version catalog manages it), so pin
 * the same version that the RN version catalog resolves to.
 */
function pinAgpClasspathVersion(contents: string, projectRoot: string): string {
  if (/com\.android\.tools\.build:gradle:(?!['"])/g.test(contents)) {
    // Already has version — idempotent.
    return contents;
  }
  let agp: string | null = null;
  try {
    const rnPkg = require.resolve('react-native/package.json', { paths: [projectRoot] });
    const toml = fs.readFileSync(
      path.join(path.dirname(rnPkg), 'gradle', 'libs.versions.toml'),
      'utf8'
    );
    agp = toml.match(/^\s*agp\s*=\s*"([^"]+)"/m)?.[1] ?? null;
  } catch { /* not found — skip */ }
  if (!agp) return contents;
  return contents.replace(
    /com\.android\.tools\.build:gradle(?!:)/g,
    `com.android.tools.build:gradle:${agp}`
  );
}

/**
 * Adds Maven repositories and vendor Gradle plugin classpaths to root build.gradle.
 * Idempotent. Supports the Groovy build.gradle generated by Expo prebuild.
 */
export const withDooPushRootBuildGradle: ConfigPlugin<PluginConfig> = (config, validated) => {
  return withProjectBuildGradle(config, (cfg) => {
    let contents = cfg.modResults.contents;

    const addAllProjectsRepo = (repo: string, marker: string) => {
      const allprojectsStart = contents.search(/allprojects\s*{/);
      if (allprojectsStart >= 0) {
        const searchArea = contents.slice(allprojectsStart);
        if (searchArea.includes(marker)) return;
      }

      contents = contents.replace(
        /allprojects\s*{\s*repositories\s*{/,
        `allprojects {\n    repositories {\n        ${repo}`
      );
    };

    const addBuildscriptRepo = (repo: string, marker: string) => {
      const buildscriptRegex = /buildscript\s*{[\s\S]*?repositories\s*{/;
      const buildscriptStart = contents.search(/buildscript\s*{/);
      if (buildscriptStart >= 0) {
        const afterBuildscript = contents.slice(buildscriptStart);
        const dependenciesStart = afterBuildscript.search(/dependencies\s*{/);
        const searchArea = dependenciesStart >= 0
          ? afterBuildscript.slice(0, dependenciesStart)
          : afterBuildscript.split(/allprojects\s*{/)[0];
        if (searchArea.includes(marker)) return;
      }


      if (buildscriptRegex.test(contents)) {
        contents = contents.replace(buildscriptRegex, (match) => `${match}\n        ${repo}`);
      } else if (/buildscript\s*{/.test(contents)) {
        contents = contents.replace(/buildscript\s*{/, `buildscript {\n    repositories {\n        ${repo}\n    }`);
      } else {
        contents = `buildscript {\n    repositories {\n        ${repo}\n    }\n}\n\n${contents}`;
      }
    };

    const addClasspath = (dependency: string) => {
      const artifact = dependency.match(/'([^:]+:[^:]+):/)?.[1] ?? dependency;
      if (contents.includes(artifact)) return;

      if (/buildscript\s*{[\s\S]*?dependencies\s*{/.test(contents)) {
        contents = contents.replace(/(buildscript\s*{[\s\S]*?dependencies\s*{)/, `$1\n        classpath ${dependency}`);
      } else if (/buildscript\s*{/.test(contents)) {
        contents = contents.replace(/buildscript\s*{/, `buildscript {\n    dependencies {\n        classpath ${dependency}\n    }`);
      } else {
        contents = `buildscript {\n    dependencies {\n        classpath ${dependency}\n    }\n}\n\n${contents}`;
      }
    };

    addAllProjectsRepo(`maven { url 'https://jitpack.io' }`, 'jitpack.io');

    if (validated.android.vendors.fcm) {
      addClasspath("'com.google.gms:google-services:4.4.2'");
    }

    if (validated.android.vendors.hms) {
      const huaweiRepo = `maven { url 'https://developer.huawei.com/repo/' }`;
      addAllProjectsRepo(huaweiRepo, 'developer.huawei.com/repo');
      addBuildscriptRepo(huaweiRepo, 'developer.huawei.com/repo');
      addClasspath("'com.huawei.agconnect:agcp:1.9.3.302'");
    }

    if (validated.android.vendors.honor) {
      const honorRepo = `maven { url 'https://developer.hihonor.com/repo/' }`;
      addAllProjectsRepo(honorRepo, 'developer.hihonor.com/repo');
      addBuildscriptRepo(honorRepo, 'developer.hihonor.com/repo');
      addClasspath("'com.hihonor.mcs:asplugin:2.0.1.300'");
      // Honor's asplugin scans root build.gradle text for an explicit AGP version;
      // Expo SDK ≥54 omits the version (managed by the version catalog). Pin it.
      contents = pinAgpClasspathVersion(contents, cfg.modRequest.projectRoot);
    }

    // mavenLocal for development.
    addAllProjectsRepo('mavenLocal()', 'mavenLocal()');

    cfg.modResults.contents = contents;
    return cfg;
  });
};
